### ISSUE TITLE
썸네일 이미지 찌그러짐 현상

### ISSUE THREAD

**Issue by junmin-Chang** [Do-it-Comm-it/DoitCommit-front#64]
@alexrider94 게시판 썸네일 이미지 부분이 좀 찌그러지는 것 같은데 css `object-fit` 옵션으로 좀 더 괜찮아 보이게 할 수 있을지도 모르겠다는 생각이 들었네요..!

**Comment by alexrider94** [comment]
오 ㅎㅎ 한번 확인해보겠습니다!
